name: my-workflow
on: 
  workflow_dispatch:
    inputs:
      userName:
        description: 'Test user name'     
        required: true
        default: 'test1'
      tags:
        description: 'Test scenario tags'  
      number:
        description: 'Test scenario number'
        required: true
        default: '1'
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "User name: %userName%"
        echo "Tags: %tags%"
        echo "Number: %number%"